[build]
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/src/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    X-Content-Type-Options = "nosniff"
